# Generated by Django 5.1 on 2024-08-24 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_userprofile'),
        ('adminside', '0006_rename_prodect_image_product_product_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_quantity', models.IntegerField()),
                ('total_price', models.IntegerField()),
                ('cart_product', models.ManyToManyField(blank=True, related_name='cart_product', to='adminside.product')),
            ],
        ),
    ]
