# Generated by Django 5.1 on 2024-08-25 12:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_usercart'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercart',
            name='cart_user',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='User_Cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
