# Generated by Django 5.1 on 2024-08-26 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_usercart_cart_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='product_quantity',
            field=models.IntegerField(default=1),
        ),
    ]
