# Generated by Django 5.1 on 2024-08-26 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_usercart_product_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='total_price',
            field=models.IntegerField(null=True),
        ),
    ]
