# Generated by Django 5.1 on 2024-08-26 17:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_usercart_total_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='cart_user',
        ),
        migrations.AddField(
            model_name='usercart',
            name='user_cart',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
