# Generated by Django 5.1 on 2024-08-26 17:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_remove_usercart_cart_user_usercart_user_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercart',
            name='user_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cart', to=settings.AUTH_USER_MODEL),
        ),
    ]
