# Generated by Django 5.1 on 2024-09-02 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_usercart_user_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='zip_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
