# Generated by Django 5.1 on 2024-09-03 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_userprofile_zip_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
    ]
