# Generated by Django 5.1 on 2024-09-03 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_account_first_name_remove_account_last_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
