# Generated by Django 5.1 on 2024-09-25 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
