# Generated by Django 5.0.6 on 2024-07-26 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=250)),
                ('catogory_image', models.ImageField(blank=True, upload_to='photos/category')),
                ('description', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Specification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ram', models.IntegerField()),
                ('gb', models.IntegerField()),
                ('main_camera', models.IntegerField()),
                ('front_camera', models.IntegerField()),
                ('processor', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prodect_name', models.CharField(max_length=250)),
                ('prodect_image', models.ImageField(blank=True, upload_to='photos/product')),
                ('product_price', models.IntegerField()),
                ('product_color', models.CharField(max_length=250)),
                ('discription', models.CharField()),
                ('stock', models.IntegerField()),
                ('is_available', models.BooleanField(default=True)),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adminside.category')),
                ('product_spec', models.ManyToManyField(blank=True, related_name='product_spec', to='adminside.specification')),
            ],
        ),
    ]
