# Generated by Django 5.0.6 on 2024-07-30 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='catogory_image',
            new_name='category_image',
        ),
    ]
