# Generated by Django 5.0.6 on 2024-08-15 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0003_rename_discription_product_product_discription_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specification',
            name='front_camera',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='specification',
            name='gb',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='specification',
            name='main_camera',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='specification',
            name='ram',
            field=models.CharField(),
        ),
    ]
