# Generated by Django 5.0.6 on 2024-08-15 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0004_alter_specification_front_camera_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specification',
            old_name='gb',
            new_name='memory',
        ),
    ]
