# Generated by Django 5.0.6 on 2024-08-15 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminside', '0005_rename_gb_specification_memory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prodect_image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='prodect_name',
            new_name='product_name',
        ),
        migrations.AlterField(
            model_name='product',
            name='product_discription',
            field=models.CharField(max_length=500),
        ),
    ]
