# Generated by Django 5.1 on 2024-09-02 10:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0009_userprofile_zip_code'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('packing_charge', models.IntegerField(default=50)),
                ('delivery_charge', models.IntegerField()),
                ('payment_method', models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on delivary')], max_length=3)),
                ('cart_details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_details', to='account.usercart')),
                ('paid_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paid_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
