# Generated by Django 5.1 on 2024-09-11 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0002_alter_payment_delivery_charge_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('UPI', 'UPI'), ('COD', 'Cash on delivary')], max_length=50, null=True),
        ),
    ]
