# Generated by Django 5.1 on 2024-09-19 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0003_alter_payment_payment_method'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('oreder_id', models.IntegerField()),
                ('status', models.CharField(choices=[('Order Confirmed', 'Order Confirmed'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled'), ('Replaced', 'Replaced')], default='Order Confirmed', max_length=50)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('refund', models.BooleanField(default=False)),
                ('replace_reason', models.CharField(blank=True, choices=[('Unhope Product', 'Unhope Produc'), ('Unlike', 'Unlike'), ('Too Heavey', 'Too Heavey')], max_length=50, null=True)),
                ('oreder_details', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='oreder_details', to='userside.payment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
