# Generated by Django 5.1 on 2024-09-19 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0004_userorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorder',
            name='oreder_id',
            field=models.CharField(),
        ),
    ]
