# Generated by Django 5.1 on 2024-09-23 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0005_alter_userorder_oreder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorder',
            old_name='oreder_details',
            new_name='order_details',
        ),
        migrations.RenameField(
            model_name='userorder',
            old_name='oreder_id',
            new_name='order_id',
        ),
    ]
