# Generated by Django 5.1 on 2024-09-25 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0008_address_default'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='default',
            new_name='default_address',
        ),
    ]
