# Generated by Django 5.1 on 2024-09-26 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userside', '0009_rename_default_address_default_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='address_line',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='address',
            name='land_mark',
            field=models.CharField(max_length=250, null=True),
        ),
    ]
